"""databse created

Revision ID: 7278f8ddde17
Revises: 
Create Date: 2025-11-30 13:26:23.442457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7278f8ddde17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('device_zone', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_name'), 'devices', ['device_name'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('heat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heat_id'), 'heat', ['id'], unique=False)
    op.create_table('humidity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humidity_id'), 'humidity', ['id'], unique=False)
    op.create_table('vibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vibration', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vibrations_id'), 'vibrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vibrations_id'), table_name='vibrations')
    op.drop_table('vibrations')
    op.drop_index(op.f('ix_humidity_id'), table_name='humidity')
    op.drop_table('humidity')
    op.drop_index(op.f('ix_heat_id'), table_name='heat')
    op.drop_table('heat')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_name'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
